### PR TITLE
Fix the "growing intersection" bug that happens when repeatedly using

### LINKED ISSUE #655: Wrong junction geometry with Modify Entire Road tool
I was playing around with the experimental Modify Entire Road and encounter some issue with the tool. I deleted a lane and add back a lane then the junction become insanely huge and the road link turns into a tiny segment. Here is a screen shot.

### PR DESCRIPTION
**Pull request by dabreegster**
the new road editor, by "untrimming" the road center points. Fixes #655

Before, you could pick a single lane and shift it left and right repeatedly, with the intersection polygon becoming subject to increasingly Lovecraftian geometry:
Screenshot from 2021-05-19 15-02-11
Screenshot from 2021-05-19 15-02-16
Truly the stuff of horrors.

Now, Cthulu has been coaxed back into the salty depths:
screencast

@tungchifung, if you happen to be building from source, feel free to checkout this branch and test it out. If not, it'll appear in this Sunday's release

### CODE REVIEW

File: map_model/src/objects/road.rs [hunk 1]
```diff
@@ -151,10 +151,12 @@ pub struct Road {
...
 
-    /// The physical center of the road, including sidewalks, after trimming. The order implies
-    /// road orientation. No edits ever change this.
-    // TODO Maybe deprecated in favor of get_left_side?
+    /// The physical center of the road, including sidewalks, after trimming to account for the
+    /// intersection geometry. The order implies road orientation.
     pub center_pts: PolyLine,
+    /// Like center_pts, but before any trimming for intersection geometry. This is preserved so
+    /// that when modifying road width, intersection polygons can be calculated correctly.
+    pub(crate) untrimmed_center_pts: PolyLine,
```
Comment (dabreegster) [inline map_model/src/objects/road.rs:159]: I was hesitant to increase map size by adding this, but it appears negligible. `south_seattle` goes from 78MB to 79MB. I can think of some complicated ways to store less points here, but I don't think it's worth the trouble.

**Review by michaelkirk — APPROVED** [review]
LGTM

**Comment by dabreegster** [comment]
I'm ironing out the last kinks in the cloud importer, since this is a binary map format change. Almost got it...
