### PR TITLE
Stop crashing for duplicate adjacent points. #1061

### LINKED ISSUE #1005: The app crashed! Nothing will work now; you have to refresh the page.
```
panicked at 'called `Result::unwrap()` on an `Err` value: Line from Pt2D { x: 5857.4217, y: 4813.787 } to Pt2D { x: 5857.4205, y: 4813.7771 } too small', geom/src/line.rs:25:29
```

To reproduce go to the following URL: https://play.abstreet.org/0.3.34/osm_viewer.html?system/nl/groningen/maps/huge.bin&--cam=19.31/53.21590/6.56499

### PR DESCRIPTION
**Pull request by dabreegster**
This is a simple first step towards the goal described in the issue.

Closes #1005 and #1051. I tested a few end-to-end things in this repo.

### CODE REVIEW

File: geom/src/polyline.rs [hunk 1]
```diff
@@ -1005,12 +998,7 @@ impl PolyLine {
     }
 
     pub(crate) fn to_geo(&self) -> geo::LineString {
-        let pts: Vec<geo::Point> = self
-            .pts
-            .iter()
-            .map(|pt| geo::Point::new(pt.x(), pt.y()))
-            .collect();
-        pts.into()
+        geo::LineString::from(self)
```
Comment (dabreegster) [inline geom/src/polyline.rs:1001]: Just a small refactoring, no need for two versions of this code
